import { WordleWord } from "./types";

export const wordleWords: WordleWord[] = [
  { word: "LIEBE", translation: "любовь", hint: "Самое важное слово 💕", emoji: "❤️" },
  { word: "TANZE", translation: "танцую", hint: "То что ты любишь делать 💃", emoji: "💃" },
  { word: "HUNDE", translation: "собаки", hint: "Лучшие друзья человека 🐶", emoji: "🐶" },
  { word: "SUSHI", translation: "суши", hint: "Твоё любимое блюдо 🍣", emoji: "🍣" },
  { word: "REISE", translation: "путешествие", hint: "То что делает жизнь богаче ✈️", emoji: "✈️" },
  { word: "DANKE", translation: "спасибо", hint: "Вежливое слово 🙏", emoji: "🙏" },
  { word: "HALLO", translation: "привет", hint: "Первое что учат на любом языке 👋", emoji: "👋" },
  { word: "BITTE", translation: "пожалуйста", hint: "Ещё одно вежливое слово 😊", emoji: "😊" },
  { word: "GUTEN", translation: "хороший", hint: "«___ Morgen!» — так говорят утром 🌅", emoji: "🌅" },
  { word: "HEUTE", translation: "сегодня", hint: "Не вчера и не завтра 📅", emoji: "📅" },
  { word: "ABEND", translation: "вечер", hint: "Время после работы 🌆", emoji: "🌆" },
  { word: "STADT", translation: "город", hint: "Цюрих — это... 🏙️", emoji: "🏙️" },
  { word: "NICHT", translation: "не / нет", hint: "Слово отрицания 🚫", emoji: "🚫" },
  { word: "HABEN", translation: "иметь", hint: "Один из главных глаголов 📌", emoji: "📌" },
  { word: "MACHE", translation: "делаю", hint: "Действие, процесс ⚡", emoji: "⚡" },
  { word: "KOMME", translation: "приходить", hint: "Движение к месту 🚶", emoji: "🚶" },
  { word: "FAHRE", translation: "еду", hint: "На машине или поезде 🚗", emoji: "🚗" },
  { word: "MUSIK", translation: "музыка", hint: "Мелодии и ритмы 🎵", emoji: "🎵" },
  { word: "BLUME", translation: "цветок", hint: "Растёт в саду, красиво пахнет 🌸", emoji: "🌸" },
  { word: "PIZZA", translation: "пицца", hint: "Итальянское блюдо 🍕", emoji: "🍕" },
  { word: "KATZE", translation: "кошка", hint: "Мяукает и мурлычет 🐱", emoji: "🐱" },
  { word: "SONNE", translation: "солнце", hint: "Светит на небе ☀️", emoji: "☀️" },
  { word: "REGEN", translation: "дождь", hint: "Капли с неба 🌧️", emoji: "🌧️" },
  { word: "WOCHE", translation: "неделя", hint: "7 дней 📆", emoji: "📆" },
  { word: "STEAK", translation: "стейк", hint: "Мясное блюдо 🥩", emoji: "🥩" },
  { word: "APRIL", translation: "апрель", hint: "Весенний месяц 🌷", emoji: "🌷" },
  { word: "NACHT", translation: "ночь", hint: "Тёмное время суток 🌙", emoji: "🌙" },
  { word: "ESSEN", translation: "еда / есть", hint: "Что мы делаем за столом 🍽️", emoji: "🍽️" },
  { word: "WARTE", translation: "жду", hint: "Стоишь и ждёшь кого-то ⏰", emoji: "⏰" },
  { word: "LERNE", translation: "учусь", hint: "Что ты делаешь прямо сейчас! 📚", emoji: "📚" },
  { word: "SPIEL", translation: "игра", hint: "Развлечение и веселье 🎮", emoji: "🎮" },
  { word: "GERNE", translation: "с удовольствием", hint: "Когда что-то нравится делать 😊", emoji: "💖" },
  { word: "TANZT", translation: "танцует", hint: "Движение под музыку 💃", emoji: "🩰" },
  { word: "MILCH", translation: "молоко", hint: "Белый напиток 🥛", emoji: "🥛" },
  { word: "KLEID", translation: "платье", hint: "Красивая женская одежда 👗", emoji: "👗" },
  { word: "BRIEF", translation: "письмо", hint: "Пишут на бумаге ✉️", emoji: "✉️" },
  { word: "SUPER", translation: "супер", hint: "Когда всё отлично! ⭐", emoji: "⭐" },
  { word: "STERN", translation: "звезда", hint: "Мерцает на небе ⭐", emoji: "🌟" },
  { word: "TOAST", translation: "тост", hint: "Поджаренный хлеб 🍞", emoji: "🍞" },
  { word: "SALAT", translation: "салат", hint: "Зелёное и полезное 🥗", emoji: "🥗" },
  { word: "KARTE", translation: "карта / открытка", hint: "Можно послать по почте 🗺️", emoji: "🗺️" },
  { word: "YACHT", translation: "яхта", hint: "Плавает по морю ⛵", emoji: "⛵" },
  { word: "NUDEL", translation: "лапша", hint: "Длинная и вкусная 🍝", emoji: "🍝" },
  { word: "HOBBY", translation: "хобби", hint: "Чем занимаешься в свободное время 🎨", emoji: "🎨" },
  { word: "TIGER", translation: "тигр", hint: "Полосатая большая кошка 🐯", emoji: "🐯" },
  { word: "PARTY", translation: "вечеринка", hint: "Музыка, танцы, веселье 🎉", emoji: "🎉" },
  { word: "MONAT", translation: "месяц", hint: "Примерно 30 дней 📅", emoji: "🗓️" },
  { word: "SCHUH", translation: "ботинок", hint: "Носишь на ногах 👟", emoji: "👟" },
  { word: "PAKET", translation: "посылка", hint: "Приходит по почте 📦", emoji: "📦" },
  { word: "KIOSK", translation: "киоск", hint: "Маленький магазинчик 🏪", emoji: "🏪" },
];
